In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [5]:
iris = load_iris(as_frame=True)
x = iris.data[["petal length (cm)", "petal width (cm)"]].values
y = (iris.target == 2)

In [6]:
svm_clf = make_pipeline(StandardScaler(), LinearSVC(C=1, random_state=42))
svm_clf.fit(x, y)
svm_clf.predict([[5.5, 1.7]])

array([ True])

In [8]:
x_new = np.array([[5.5, 1.7]])
svm_clf.predict(x_new)


array([ True])

In [9]:
svm_clf.decision_function(x_new)

array([0.66163816])